### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by kevintransp** [Krizfrost/esx_civliferp_identity#1]
Good day,
I'm a little bit confused about to do or do not delete the character table. In the readme its says delete no longer used but in the update sql file he wants to place the table back again.

Tell me all about is please.
Kind regard,
Kevin.

**Comment by KrizKhaoz** [comment]
Do not follow the esx_identity readme download the latest esx_identity and import the __resource.lua and the HTML folder that I provide in this resource and it should work fine.
